update html css
ivanbilobrov07/Simply-Chocolate pull request #9
Opened 2023-04-07 22:41 UTC by HannaBonda

2023-04-08 04:20 UTC, VladyslavSimahin requested changes

2023-04-08 04:20 UTC, VladyslavSimahin commented on src/css/top-sellers.css
> +@media screen and (min-width: 330px) and (max-width: 1199px) {
тут лібше дати тільки max-width:1199px

2023-04-08 04:20 UTC, VladyslavSimahin commented on src/partials/top-sellers.html
> +        <button type="button" class="sellers-button">Buy now</button>
якщо кнопка не стала на своє місце можеш обгорнути в div і потім зможеш поставити в кінець

2023-04-09 15:30 UTC, ivanbilobrov07 approved these changes
Well done

2023-04-09 15:53 UTC, merged